version: '3.1'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
      MYSQL_USER: dpuc
      MYSQL_PASSWORD: abcd12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  app:
    build: .
    container_name: test_app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/users_db
      SPRING_DATASOURCE_USERNAME: dpuc
      SPRING_DATASOURCE_PASSWORD: abcd12345
    ports:
      - "8080:8080"

volumes:
  mysql-data:
