version: '3.1'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_USER: root
      MYSQL_PASSWORD: abcd12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  users-service:
    image: users-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
